### ISSUE TITLE
Reset Index counter in Watcher view on reset

### ISSUE THREAD

**Issue by wollsi** [LukasLoeffler/pgtools#12]
When reseting the Watcher view, the Index starts counting at the old value. It would be nice to reset the index counter as well.

**Comment by LukasLoeffler** [comment]
Can confirm. Will fix this issue soon.

**Comment by LukasLoeffler** [comment]
The

**Comment by LukasLoeffler** [comment]
The issue was fixed in Release v1.1.2.
